### ISSUE TITLE
Voltage typically 3.2-4.2v

### ISSUE THREAD

**Issue by BillyBag2** [liamcottle/meshtastic-map#13]
The voltage graph min could be set to minimum of 3.2v and all measurements. The maximum to the maximum of 4.2 volts and all measurements. The voltage and battery % would look then look similar. (I don't think they follow each other in all cases and the relationship may not be linear)

At the time of writing min v looked to be 0v and the voltage graph was difficult to see as the line was only at the top.

**Comment by fifieldt** [comment]
After #23 was merged, spend a couple weeks trying the new graph ranges and felt it could be better.

Quick data analysis supports increasing min voltage to 3v; fewer than 0.1% of nodes have a voltage less than this.

![image](https://github.com/liamcottle/meshtastic-map/assets/1287116/de6c4111-a35d-4001-9986-63188438a42c)
