### ISSUE TITLE
Cleanup sidebar

### ISSUE THREAD

**Issue by GMart** [liamcottle/meshtastic-map#21]
Hi,
Ideas for the sidebar. I think it's getting really long, even on a 1440p screen. 
Here is what I suggest:
The separator could be a line, comma, table, etc.

- Put Long and short name into one row, with some sort of separator. 
- Put Role and firmware into one row
- Put Region and frequency into one row
- Put Modem Preset and Has Default into one row
- Put Lat and Long into one row
- Maybe? Battery level and volt into one row?
- ID and Hex ID into one row
- Neighbors updated and Position updated into one row.

Thanks

**Comment by liamcottle** [comment]
Hey! I've made significant changes to the sidebar over the last couple of days. Most of this has been done, still some more I will look into doing as time goes on. Closing this out for now :)
