### ISSUE TITLE
FR - Node tracking

### ISSUE THREAD

**Issue by nukemrules** [liamcottle/meshtastic-map#26]
First of all, thank you for your great work. I'm a thankful every day user of the map.

Back in the day's I've looked at APRS. Some of the bigger APRS sites (https://aprs.fi) do offer tracking of a station automatically. This way you can backtrack where the node has been. It will plot its route by dots and colored lines.

Perhaps this could be a useful option to have on your map? 

I do have some requests:
1. For privacy reasons only look back for 1, 2 or 3 hours?
2. Add info to the plotted dots who heard that node on that location. It will help to identify coverage issues.

**Comment by liamcottle** [comment]
Thanks for the feature request and for the feedback :)

I merged in #54 that implemented this feature the other week, and it caused quite the controversy in the Meshtastic discord...

Anyway, I'll close this out as being completed.
