### ISSUE TITLE
Decoupling mqtt listener and web ui

### ISSUE THREAD

**Issue by KomelT** [liamcottle/meshtastic-map#42]
As I wrote in the issue title, it would be smart if the mqtt listener and web UI were decoupled. This is a draft of how it would look:

```
meshtastic-map
├── docker-compose.yaml
├── mqtt-listener
│  └── dockerfile
├── prisma
└── web
   └── dockerfile
```

I think it would be also a good time to add a proper vue js build process as you wrote in To Do.
And I think implementing Docker would help to easily self host the project.

**Comment by liamcottle** [comment]
I think the file structure is fine as is.

Also, support for docker compose is now available in the main branch thanks to @ketan.

Might revisit doing a proper build process in the future, but it's not a priority.

Closing this for now :)
