### ISSUE TITLE
A long disabled node remains on the map

### ISSUE THREAD

**Issue by Holyszewski** [liamcottle/meshtastic-map#45]
For some reason, a node that has been disabled for over a week remains displayed on the map.
The node is displayed on the map with the information "MQTT Status: Online (3 minutes ago)".
I don't understand why this is the case, the node has really been turned off for over a week.

ID: 3663107308
Hex ID: !da5694ec
https://meshtastic.liamcottle.net/?node_id=3663107308
![Snímek obrazovky 2024-07-01 125050](https://github.com/liamcottle/meshtastic-map/assets/75616137/124326ed-5194-43d2-a698-1d6438d37cf2)

**Comment by liamcottle** [comment]
This is most likely happening when I restart the map server, or my server disconnects and reconnects to to the Meshtastic MQTT server.

When connecting to the Meshtastic MQTT server, it sends all of the persistent `stat` packets with `online` or `offline` for each node ID it has in memory.

These packets are used to update the MQTT status shown on the node info popup. So even if your node is completely offline, or no longer exists, the MQTT still sends these packets on server reconnection, and I update them in my database.

This also updates the last seen timestamp as well, which would be why it's changing. Last Seen is actually just the `updated_at` column from the database. It's not based on when the last radio packet was heard.

If you really want, I can just delete this node from the database, and if it comes back online at all, it will be recreated.
