### ISSUE TITLE
See more than 24 hours of battery history in node details

### ISSUE THREAD

**Issue by Sparkling-Ice** [liamcottle/meshtastic-map#46]
For solar nodes, being able to track battery life over longer than a 24 hour period would be great.
I see that there are other issues about cleaning up the sidebar (e.g. #21 ), but having extended battery stats would be very beneficial for solar node operators due to weather affecting solar power collection.
Could the battery graph be dropped to a new line below battery level and percentage, in order to take up the whole side bar, instead of just the right column of it's row? Then you could show 48+ hours of data hopefully.

**Comment by liamcottle** [comment]
Thanks for the feature request! I have implemented a new device metrics chart with a style inspired by the official iOS app.

At this stage, it shows the last 3 days of metrics. I might add a dropdown to change the range in the future.

![image](https://github.com/user-attachments/assets/b2e0f321-2dbe-4923-bfd6-d48b30bc3ecd)
