### ISSUE TITLE
Save last position and relative zoom level upon page refresh

### ISSUE THREAD

**Issue by GMart** [liamcottle/meshtastic-map#5]
Feature request:
Save the map position, so when refreshing the entire page, it doesn't reset to a globe view. You could add a maximum saved zoom level so it won't be zoomed in too much, maybe max zoom level of 10 or something.

**Comment by liamcottle** [comment]
Thanks for the request!

There is a new `Auto Update Position in URL` checkbox in the settings panel.
It will automatically set `lat`, `lng` and `zoom` in the url, allowing you to refresh the page or share the link that will load the map at the current position.

Let me know if you have any other ideas.
