### ISSUE TITLE
UX: add message created timestamp as tooltip

### ISSUE THREAD

**Issue by nikmess** [liamcottle/meshtastic-map#58]
If you changed 
https://github.com/liamcottle/meshtastic-map/blob/f6f0970d21df5ac5a4b321239ab52cb46cbce0cd/src/public/text-messages-embed.html#L64
to
```html
<div class="w-full space-y-0.5 px-2.5 py-1" v-bind:title="message.created_at" v-html="escapeMessageText(message.text)"></div>
```
we'd see the time the respective message was sent/forwarded on hovering over the text.

**Comment by liamcottle** [comment]
Made a few updates to the messages UI today, you can now click the message content to reveal when the message was received via MQTT. You can hover the text on desktop to show the full datetime string. I might show this by default in the future, but didn't want to clutter the UI too much. Closing this for now :)
