### ISSUE TITLE
Can't click on Show Full Details sometimes

### ISSUE THREAD

**Issue by GMart** [liamcottle/meshtastic-map#6]
Bug:
1. Search for a node and select it
2. It zooms into that node
3. I'm unable to click on "Show Full Details"

If I click elsewhere, then click back on the node, I can click the button.

I tried on Edge and Chrome, it might work elsewhere?

**Comment by liamcottle** [comment]
Bug was specific to tooltips opened via the `goToNode` method. Fixed in 261ab9fe61b4049ded2eb7d3f2e5359c45c084b6
