### ISSUE TITLE
How to list only node data

### ISSUE THREAD

**Issue by uguraltinsoy** [liamcottle/meshtastic-map#70]
In this project, how can I list only the connected nodes and display only the device information and locations without using a map? For example, I want it to function like an API that returns a dataset when queried.

**Comment by liamcottle** [comment]
You can query the API endpoints that the map interface uses, such as:

- https://meshtastic.liamcottle.net/api/v1/nodes
- https://meshtastic.liamcottle.net/api/v1/nodes/3944424993
- https://meshtastic.liamcottle.net/api/v1/nodes/3944424993/device-metrics

There's more APIs than these, but I won't list them all here. You can see what endpoints are available in the source code:

- https://github.com/liamcottle/meshtastic-map/blob/master/src/index.js

Of course, if you are self hosting the map, you can update the URL to point to your own instance instead.
