### ISSUE TITLE
Research: Multiple nodes with the same ID !6e2718a

### ISSUE THREAD

**Issue by CamFlyerCH** [liamcottle/meshtastic-map#72]
By accident I found a the node ID !6e2718a that probably is set on my many Meshtastic nodes. It is always a RAK4631. The battery state fluctuates a lot between different values. 

![image](https://github.com/user-attachments/assets/a0c8d798-e352-4fc0-96f2-6b4d6837a474)

This is NOT an issue with this map ! Also the Meshmap indicates the issue my showing MQTT nodes receiving this ID from different continents in a short time :
![image](https://github.com/user-attachments/assets/4c264632-5a8f-4b04-a4b4-fb16c52ef494)

Also visible in the position history:
![image](https://github.com/user-attachments/assets/428d1ccd-b4f8-423e-8dbf-6a3a83642d20)

I was thinking you could probably extract more data from nodeinfo packets you MQTT server received to understand this issue better. I don't know how the ID is exactly generated and how one affected user can change it. I hope this is interesting for you too. I wonder if there are other IDs affected by this. I did not find the official documentation for the way the ID is generated. According to different LLMs the BT Mac address is used , but probably also other things.

**Comment by Forge36** [comment]
Applicate of #47 ?

**Comment by liamcottle** [comment]
Some messages related to this in the Meshtastic Discord:

- https://discord.com/channels/867578229534359593/871553024030556250/1279051666246864896
- https://discord.com/channels/867578229534359593/871553024030556250/1267431315817500692

> I don't know how the ID is exactly generated and how one affected user can change it.

As far as I know, the solution is to factory reset the device, in which case it will then re-generate the node ID based on the actual hardware BLE mac address.

I had a couple of "new" nodes that had weird IDs, and factory resetting them did in fact resolve the issue.

<img width="1038" alt="Screenshot 2024-09-17 at 12 44 41 AM" src="https://github.com/user-attachments/assets/44a06c62-d98e-43ca-9e78-0acd9eae39e3">

**Comment by CamFlyerCH** [comment]
OK, thanks for that. I was not able to find these. My bad or the fault of duckduckgo. In this case all is clear now. I hope the affected people have no nodes in range with the same ID or find the solution as mentioned on Discord.
