### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by hassos246** [liamcottle/meshtastic-map#78]
I have my node connected to a local mqtt broker. Is it possible to bridge this broker to the map. Or are a separate node needed to connect to the map?

**Comment by CamFlyerCH** [comment]
I do that. Did you manage to do it or do you need help ?

**Comment by hassos246** [comment]
I got help on Discord.

**Comment by nomore1007** [comment]
I could use help, or at least pointed in the right direction. I have what I think is my broker bridged, but it's not showing up.
