### ISSUE TITLE
Running Docker gives Options Error

### ISSUE THREAD

**Issue by skykingisepic** [liamcottle/meshtastic-map#80]
Since I can't get the server to update the db using node directly, I decided to run Docker.

docker compose up yields this error:

meshtastic-mqtt  | UNKNOWN_VALUE: Unknown value: mqtt-broker-url

docker-compose.yml:
MQTT_OPTS: "mqtt-broker-url mqtt://epicnet.us:8183 mqtt-username MeshEastTN mqtt-password private mqtt-topic msg/TN collect-service-envelopes collect-neighbour-info collect-map-reports purge-interval-seconds 43200 purge-nodes-unheard-for-seconds 172800"

**Comment by Th3H0ff** [comment]
Greetings
Could you share any info on how this was solved? I have the same issue.
