### ISSUE TITLE
temperature below 0 degrees celsius is not displayed

### ISSUE THREAD

**Issue by v7o73** [liamcottle/meshtastic-map#87]
Temperature below 0 degrees celsius is not displayed in the "Node Info" -> "Environment Metrics" chart.
Could it be extended to -10 degrees celsius?

**Comment by liamcottle** [comment]
Yep, adjusted to show down to -20ºc in https://github.com/liamcottle/meshtastic-map/commit/1b3d4c963538358857cfb4affdbbd6a9cd81f6d0

**Comment by v7o73** [comment]
thanks, it shows fine :-)
